export const serviceStatuses = [
  'pending', 'approved', 'hidden', 'rejected'
]

export const bookingStatuses = [
  'new', 'ongoing', 'completed', 'cancelled', 'missed'
]

export const vendorServicesOptions = [
  "Medical And Clinical Care",
  "Wellness And Therapy",
  "Baby Care Services",
  "Fitness And Recovery",
  "Home And Lifestyle Support",
  "Education And Coaching",
  "Products And Essentials"
]

export const currencies = ['NGN']

export const ticketFields = ['billing', 'account', 'bookings', 'services', 'other']

// Sidebar list 
export const SidebarItems = [
  { label: 'Dashboard', icon: 'material-symbols:dashboard-outline', path: '/' },
  { label: 'Services', icon: 'material-symbols:work-outline', path: '/services' },
  { label: 'Bookings', icon: 'uil:calender', path: "/bookings" },
  { label: 'Inbox', icon: 'ic:outline-message', path: "/inbox" },
  { label: 'Wallet', icon: 'ic:outline-account-balance-wallet', path: "wallet" },
];

// Dashboard Data 
export const statsData = {
  totalBookings: 2323,
  totalClients: 123423,
};

export const chartData = [
  { month: "Jan", bookings: 400 },
  { month: "Feb", bookings: 650 },
  { month: "Mar", bookings: 500 },
  { month: "Apr", bookings: 700 },
  { month: "May", bookings: 600 },
  { month: "Jun", bookings: 800 },
  { month: "Jul", bookings: 720 },
  { month: "Aug", bookings: 900 },
  { month: "Sep", bookings: 850 },
  { month: "Oct", bookings: 1000 },
  { month: "Nov", bookings: 950 },
  { month: "Dec", bookings: 1100 },
];

export const topLocations = [
  { id: 1, name: "OR4, Ikoyi, Lagos", orders: 9 },
  { id: 2, name: "Obal, Ikoyi, Lagos", orders: 8 },
  { id: 3, name: "Lekki, Lagos", orders: 6 },
  { id: 4, name: "VI, Lagos", orders: 5 },
  { id: 5, name: "Yaba, Lagos", orders: 3 },
];

export const bookingsData = [
  {
    bookingNumber: "#w3e3wq233213",
    bookingDate: "23-08-23 / 03:00 - 4:00PM",
    serviceBooked: "Baby sitting, Full body Massage",
    location: "Lekki, Lagos",
    status: "Upcoming",
  },
  {
    bookingNumber: "#w3e3wq233213",
    bookingDate: "23-08-23 / 03:00 - 4:00PM",
    serviceBooked: "Baby sitting, Full body Massage",
    location: "Lekki, Lagos",
    status: "Ongoing",
  },
  {
    bookingNumber: "#w3e3wq233213",
    bookingDate: "23-08-23 / 03:00 - 4:00PM",
    serviceBooked: "Baby sitting, Full body Massage",
    location: "Lekki, Lagos",
    status: "Attended",
  },
  {
    bookingNumber: "#w3e3wq233213",
    bookingDate: "23-08-23 / 03:00 - 4:00PM",
    serviceBooked: "Baby sitting, Full body Massage",
    location: "Lekki, Lagos",
    status: "Cancelled",
  },
  {
    bookingNumber: "#w3e3wq233213",
    bookingDate: "23-08-23 / 03:00 - 4:00PM",
    serviceBooked: "Baby sitting, Full body Massage",
    location: "Lekki, Lagos",
    status: "Missed",
  },
];

export const statusColors = {
  Upcoming: "bg-orange-100 text-orange-600",
  Ongoing: "bg-green-100 text-green-600",
  Attended: "bg-purple-100 text-purple-600",
  Cancelled: "bg-gray-100 text-gray-500",
  Missed: "bg-red-100 text-red-600",
};

export const servicesData = {
  active: 23,
  inactive: null,
}

export const services = [
  {
    id: 1,
    title: "Massage therapy",
    price: "$4000/Session",
    tags: ["Massage", "Therapy"],
    status: "Active",
    description: "Prospective clients can see this service",
  },
  {
    id: 2,
    title: "Massage therapy",
    price: "$4000/Session",
    tags: ["Massage", "Therapy"],
    status: "Hidden",
    description: "Prospective clients can not see this service",
  },
  {
    id: 3,
    title: "Massage therapy",
    price: "$4000/Session",
    tags: ["Massage", "Therapy"],
    status: "Rejected",
    description: "Service did not pass our checks",
  },
  {
    id: 4,
    title: "Massage therapy",
    price: "$4000/Session",
    tags: ["Massage", "Therapy"],
    status: "Pending",
    description: "This service is being reviewed",
  },
];

// Bookings 
export const bookingsInfo = [
  { title: "Total Bookings", value: 234, color: "bg-white", icon: null },
  { title: "Upcoming Bookings", value: 23, color: "bg-primary-50 text-warning-500", icon: "uil:calender" },
  { title: "Ongoing Bookings", value: 232, color: "bg-primary-50 text-success-500", icon: "uil:calender" },
  { title: "Completed Bookings", value: 23, color: "bg-primary-50 text-primary-500", icon: "uil:calender" },
  { title: "Missed Bookings", value: 2323, color: "bg-primary-50 text-error-500", icon: "uil:calender" },
  { title: "Cancelled Bookings", value: 32, color: "bg-primary-50 text-grey-600", icon: "uil:calender" },
];

export const bookingsTableData = [
  {
    number: "#we3ewq233213",
    date: "23-08-23 / 03:00 - 4:00PM",
    service: "Baby sitting, Full body Massage",
    location: "Lekki, Lagos",
    status: "Upcoming",
  },
  {
    number: "#we3ewq233213",
    date: "23-08-23 / 03:00 - 4:00PM",
    service: "Baby sitting, Full body Massage",
    location: "Lekki, Lagos",
    status: "Ongoing",
  },
  {
    number: "#we3ewq233213",
    date: "23-08-23 / 03:00 - 4:00PM",
    service: "Baby sitting, Full body Massage",
    location: "Lekki, Lagos",
    status: "Attended",
  },
  {
    number: "#we3ewq233213",
    date: "23-08-23 / 03:00 - 4:00PM",
    service: "Baby sitting",
    location: "Lekki, Lagos",
    status: "Cancelled",
  },
  {
    number: "#we3ewq233213",
    date: "23-08-23 / 03:00 - 4:00PM",
    service: "Baby sitting, Full body Massage",
    location: "Lekki, Lagos",
    status: "Missed",
  },
];

// Wallet 
export const walletInfo = [
  // { title: "Available Balance", value: 7200000.00, color: "bg-white text-success-500", icon: "ic:outline-account-balance-wallet" },
  { title: "Pending Balance", value: 7200000.00, color: "bg-primary-50 text-error-500", icon: "ic:outline-account-balance-wallet" },
  { title: "Withdrawn", value: 7200000.00, color: "bg-primary-50 text-grey-700", icon: "ic:outline-account-balance-wallet" },
];

export const walletTransactions = [
  {
    id: "txn1",
    withdrawalDate: "Jun 14, 2024 / 4:00PM",
    referenceId: "12392884218WERSDDAAI",
    receivingBankAccount: "Access Bank / 812171762935",
    amount: "23,000,000",
    status: "Processing",
  },
  {
    id: "txn2",
    withdrawalDate: "Jun 14, 2024 / 4:00PM",
    referenceId: "12392884218WERSDDAAI",
    receivingBankAccount: "Access Bank / 812171762935",
    amount: "23,000,000",
    status: "Success",
  },
  {
    id: "txn3",
    withdrawalDate: "Jun 14, 2024 / 4:00PM",
    referenceId: "12392884218WERSDDAAI",
    receivingBankAccount: "Access Bank / 812171762935",
    amount: "23,000,000",
    status: "Success",
  },
  {
    id: "txn4",
    withdrawalDate: "Jun 14, 2024 / 4:00PM",
    referenceId: "12392884218WERSDDAAI",
    receivingBankAccount: "Access Bank / 812171762935",
    amount: "23,000,000",
    status: "Processing",
  },
  {
    id: "txn5",
    withdrawalDate: "Jun 14, 2024 / 4:00PM",
    referenceId: "12392884218WERSDDAAI",
    receivingBankAccount: "Access Bank / 812171762935",
    amount: "23,000,000",
    status: "Failed",
  },
  {
    id: "txn6",
    withdrawalDate: "Jun 14, 2024 / 4:00PM",
    referenceId: "12392884218WERSDDAAI",
    receivingBankAccount: "Access Bank / 812171762935",
    amount: "23,000,000",
    status: "Success",
  },
  {
    id: "txn7",
    withdrawalDate: "Jun 14, 2024 / 4:00PM",
    referenceId: "12392884218WERSDDAAI",
    receivingBankAccount: "Access Bank / 812171762935",
    amount: "23,000,000",
    status: "Success",
  },
];

export const countries = [
  { value: 'nigeria', title: 'Nigeria 🇳🇬', countryCode: '+234' },
  // { value: 'ghana', title: 'Ghana 🇬🇭' },
  // { value: 'united states', title: 'United States 🇺🇸' },
  // { value: 'united kingdom', title: 'United Kingdom 🇬🇧' },
];

export const states = [
  { "title": "Abia", "value": "abia", country: 'nigeria' },
  { "title": "Adamawa", "value": "adamawa", country: 'nigeria' },
  { "title": "Akwa Ibom", "value": "akwa_ibom", country: 'nigeria' },
  { "title": "Anambra", "value": "anambra", country: 'nigeria' },
  { "title": "Bauchi", "value": "bauchi", country: 'nigeria' },
  { "title": "Bayelsa", "value": "bayelsa", country: 'nigeria' },
  { "title": "Benue", "value": "benue", country: 'nigeria' },
  { "title": "Borno", "value": "borno", country: 'nigeria' },
  { "title": "Cross River", "value": "cross_river", country: 'nigeria' },
  { "title": "Delta", "value": "delta", country: 'nigeria' },
  { "title": "Ebonyi", "value": "ebonyi", country: 'nigeria' },
  { "title": "Edo", "value": "edo", country: 'nigeria' },
  { "title": "Ekiti", "value": "ekiti", country: 'nigeria' },
  { "title": "Enugu", "value": "enugu", country: 'nigeria' },
  { "title": "Gombe", "value": "gombe", country: 'nigeria' },
  { "title": "Imo", "value": "imo", country: 'nigeria' },
  { "title": "Jigawa", "value": "jigawa", country: 'nigeria' },
  { "title": "Kaduna", "value": "kaduna", country: 'nigeria' },
  { "title": "Kano", "value": "kano", country: 'nigeria' },
  { "title": "Katsina", "value": "katsina", country: 'nigeria' },
  { "title": "Kebbi", "value": "kebbi", country: 'nigeria' },
  { "title": "Kogi", "value": "kogi", country: 'nigeria' },
  { "title": "Kwara", "value": "kwara", country: 'nigeria' },
  { "title": "Lagos", "value": "lagos", country: 'nigeria' },
  { "title": "Nasarawa", "value": "nasarawa", country: 'nigeria' },
  { "title": "Niger", "value": "niger", country: 'nigeria' },
  { "title": "Ogun", "value": "ogun", country: 'nigeria' },
  { "title": "Ondo", "value": "ondo", country: 'nigeria' },
  { "title": "Osun", "value": "osun", country: 'nigeria' },
  { "title": "Oyo", "value": "oyo", country: 'nigeria' },
  { "title": "Plateau", "value": "plateau", country: 'nigeria' },
  { "title": "Rivers", "value": "rivers", country: 'nigeria' },
  { "title": "Sokoto", "value": "sokoto", country: 'nigeria' },
  { "title": "Taraba", "value": "taraba", country: 'nigeria' },
  { "title": "Yobe", "value": "yobe", country: 'nigeria' },
  { "title": "Zamfara", "value": "zamfara", country: 'nigeria' },
  { "title": "Abuja", "value": "abuja", country: 'nigeria' }
]

export const cities = [
  { title: 'Calabar', country: 'nigeria', state: 'cross_river', value: 'calabar' }
]

export const NigerianCities = 
[
  {
    "state": "Adamawa",
    "state": "adamawa",
    "lgas": [
      "Demsa",
      "Fufure",
      "Ganye",
      "Gayuk",
      "Gombi",
      "Grie",
      "Hong",
      "Jada",
      "Larmurde",
      "Madagali",
      "Maiha",
      "Mayo Belwa",
      "Michika",
      "Mubi North",
      "Mubi South",
      "Numan",
      "Shelleng",
      "Song",
      "Toungo",
      "Yola North",
      "Yola South"
    ]
  },
  {
    "state": "Akwa Ibom",
    "state": "akwa_ibom",
    "lgas": [
      "Abak",
      "Eastern Obolo",
      "Eket",
      "Esit Eket",
      "Essien Udim",
      "Etim Ekpo",
      "Etinan",
      "Ibeno",
      "Ibesikpo Asutan",
      "Ibiono-Ibom",
      "Ikot Abasi",
      "Ika",
      "Ikono",
      "Ikot Ekpene",
      "Ini",
      "Mkpat-Enin",
      "Itu",
      "Mbo",
      "Nsit-Atai",
      "Nsit-Ibom",
      "Nsit-Ubium",
      "Obot Akara",
      "Okobo",
      "Onna",
      "Oron",
      "Udung-Uko",
      "Ukanafun",
      "Oruk Anam",
      "Uruan",
      "Urue-Offong/Oruko",
      "Uyo"
    ]
  },
  {
    "state": "Anambra",
    "state": "anambra",
    "lgas": [
      "Aguata",
      "Anambra East",
      "Anaocha",
      "Awka North",
      "Anambra West",
      "Awka South",
      "Ayamelum",
      "Dunukofia",
      "Ekwusigo",
      "Idemili North",
      "Idemili South",
      "Ihiala",
      "Njikoka",
      "Nnewi North",
      "Nnewi South",
      "Ogbaru",
      "Onitsha North",
      "Onitsha South",
      "Orumba North",
      "Orumba South",
      "Oyi"
    ]
  },
  {
    "state": "Ogun",
    "state": "ogun",
    "lgas": [
      "Abeokuta North",
      "Abeokuta South",
      "Ado-Odo/Ota",
      "Egbado North",
      "Ewekoro",
      "Egbado South",
      "Ijebu North",
      "Ijebu East",
      "Ifo",
      "Ijebu Ode",
      "Ijebu North East",
      "Imeko Afon",
      "Ikenne",
      "Ipokia",
      "Odeda",
      "Obafemi Owode",
      "Odogbolu",
      "Remo North",
      "Ogun Waterside",
      "Shagamu"
    ]
  },
  {
    "state": "Ondo",
    "state": "ondo",
    "lgas": [
      "Akoko North-East",
      "Akoko North-West",
      "Akoko South-West",
      "Akoko South-East",
      "Akure North",
      "Akure South",
      "Ese Odo",
      "Idanre",
      "Ifedore",
      "Ilaje",
      "Irele",
      "Ile Oluji/Okeigbo",
      "Odigbo",
      "Okitipupa",
      "Ondo West",
      "Ose",
      "Ondo East",
      "Owo"
    ]
  },
  {
    "state": "Rivers",
    "state": "rivers",
    "lgas": [
      "Abua/Odual",
      "Ahoada East",
      "Ahoada West",
      "Andoni",
      "Akuku-Toru",
      "Asari-Toru",
      "Bonny",
      "Degema",
      "Emuoha",
      "Eleme",
      "Ikwerre",
      "Etche",
      "Gokana",
      "Khana",
      "Obio/Akpor",
      "Ogba/Egbema/Ndoni",
      "Ogu/Bolo",
      "Okrika",
      "Omuma",
      "Opobo/Nkoro",
      "Oyigbo",
      "Port Harcourt",
      "Tai"
    ]
  },
  {
    "state": "Bauchi",
    "state": "bauchi",
    "lgas": [
      "Alkaleri",
      "Bauchi",
      "Bogoro",
      "Damban",
      "Darazo",
      "Dass",
      "Gamawa",
      "Ganjuwa",
      "Giade",
      "Itas/Gadau",
      "Jama'are",
      "Katagum",
      "Kirfi",
      "Misau",
      "Ningi",
      "Shira",
      "Tafawa Balewa",
      "Toro",
      "Warji",
      "Zaki"
    ]
  },
  {
    "state": "Benue",
    "state": "benue",
    "lgas": [
      "Agatu",
      "Apa",
      "Ado",
      "Buruku",
      "Gboko",
      "Guma",
      "Gwer East",
      "Gwer West",
      "Katsina-Ala",
      "Konshisha",
      "Kwande",
      "Logo",
      "Makurdi",
      "Obi",
      "Ogbadibo",
      "Ohimini",
      "Oju",
      "Okpokwu",
      "Oturkpo",
      "Tarka",
      "Ukum",
      "Ushongo",
      "Vandeikya"
    ]
  },
  {
    "state": "Borno",
    "state": "borno",
    "lgas": [
      "Abadam",
      "Askira/Uba",
      "Bama",
      "Bayo",
      "Biu",
      "Chibok",
      "Damboa",
      "Dikwa",
      "Guzamala",
      "Gubio",
      "Hawul",
      "Gwoza",
      "Jere",
      "Kaga",
      "Kala/Balge",
      "Konduga",
      "Kukawa",
      "Kwaya Kusar",
      "Mafa",
      "Magumeri",
      "Maiduguri",
      "Mobbar",
      "Marte",
      "Monguno",
      "Ngala",
      "Nganzai",
      "Shani"
    ]
  },
  {
    "state": "Bayelsa",
    "state": "bayelsa",
    "lgas": [
      "Brass",
      "Ekeremor",
      "Kolokuma/Opokuma",
      "Nembe",
      "Ogbia",
      "Sagbama",
      "Southern Ijaw",
      "Yenagoa"
    ]
  },
  {
    "state": "Cross River",
    "state": "cross_river",
    "lgas": [
      "Abi",
      "Akamkpa",
      "Akpabuyo",
      "Bakassi",
      "Bekwarra",
      "Biase",
      "Boki",
      "Calabar Municipal",
      "Calabar South",
      "Etung",
      "Ikom",
      "Obanliku",
      "Obubra",
      "Obudu",
      "Odukpani",
      "Ogoja",
      "Yakuur",
      "Yala"
    ]
  },
  {
    "state": "Delta",
    "state": "delta",
    "lgas": [
      "Aniocha North",
      "Aniocha South",
      "Bomadi",
      "Burutu",
      "Ethiope West",
      "Ethiope East",
      "Ika North East",
      "Ika South",
      "Isoko North",
      "Isoko South",
      "Ndokwa East",
      "Ndokwa West",
      "Okpe",
      "Oshimili North",
      "Oshimili South",
      "Patani",
      "Sapele",
      "Udu",
      "Ughelli North",
      "Ukwuani",
      "Ughelli South",
      "Uvwie",
      "Warri North",
      "Warri South",
      "Warri South West"
    ]
  },
  {
    "state": "Ebonyi",
    "state": "ebonyi",
    "lgas": [
      "Abakaliki",
      "Afikpo North",
      "Ebonyi",
      "Afikpo South",
      "Ezza North",
      "Ikwo",
      "Ezza South",
      "Ivo",
      "Ishielu",
      "Izzi",
      "Ohaozara",
      "Ohaukwu",
      "Onicha"
    ]
  },
  {
    "state": "Edo",
    "state": "edo",
    "lgas": [
      "Akoko-Edo",
      "Egor",
      "Esan Central",
      "Esan North-East",
      "Esan South-East",
      "Esan West",
      "Etsako Central",
      "Etsako East",
      "Etsako West",
      "Igueben",
      "Ikpoba Okha",
      "Orhionmwon",
      "Oredo",
      "Ovia North-East",
      "Ovia South-West",
      "Owan East",
      "Owan West",
      "Uhunmwonde"
    ]
  },
  {
    "state": "Ekiti",
    "state": "ekiti",
    "lgas": [
      "Ado Ekiti",
      "Efon",
      "Ekiti East",
      "Ekiti South-West",
      "Ekiti West",
      "Emure",
      "Gbonyin",
      "Ido Osi",
      "Ijero",
      "Ikere",
      "Ilejemeje",
      "Irepodun/Ifelodun",
      "Ikole",
      "Ise/Orun",
      "Moba",
      "Oye"
    ]
  },
  {
    "state": "Enugu",
    "state": "enugu",
    "lgas": [
      "Awgu",
      "Aninri",
      "Enugu East",
      "Enugu North",
      "Ezeagu",
      "Enugu South",
      "Igbo Etiti",
      "Igbo Eze North",
      "Igbo Eze South",
      "Isi Uzo",
      "Nkanu East",
      "Nkanu West",
      "Nsukka",
      "Udenu",
      "Oji River",
      "Uzo Uwani",
      "Udi"
    ]
  },
  {
    "state": "Federal Capital Territory",
    "state": "abuja",
    "lgas": [
      "Abaji",
      "Bwari",
      "Gwagwalada",
      "Kuje",
      "Kwali",
      "Municipal Area Council"
    ]
  },
  {
    "state": "Gombe",
    "state": "gombe",
    "lgas": [
      "Akko",
      "Balanga",
      "Billiri",
      "Dukku",
      "Funakaye",
      "Gombe",
      "Kaltungo",
      "Kwami",
      "Nafada",
      "Shongom",
      "Yamaltu/Deba"
    ]
  },
  {
    "state": "Jigawa",
    "state": "jigawa",
    "lgas": [
      "Auyo",
      "Babura",
      "Buji",
      "Biriniwa",
      "Birnin Kudu",
      "Dutse",
      "Gagarawa",
      "Garki",
      "Gumel",
      "Guri",
      "Gwaram",
      "Gwiwa",
      "Hadejia",
      "Jahun",
      "Kafin Hausa",
      "Kazaure",
      "Kiri Kasama",
      "Kiyawa",
      "Kaugama",
      "Maigatari",
      "Malam Madori",
      "Miga",
      "Sule Tankarkar",
      "Roni",
      "Ringim",
      "Yankwashi",
      "Taura"
    ]
  },
  {
    "state": "Oyo",
    "state": "oyo",
    "lgas": [
      "Afijio",
      "Akinyele",
      "Atiba",
      "Atisbo",
      "Egbeda",
      "Ibadan North",
      "Ibadan North-East",
      "Ibadan North-West",
      "Ibadan South-East",
      "Ibarapa Central",
      "Ibadan South-West",
      "Ibarapa East",
      "Ido",
      "Ibarapa North",
      "Irepo",
      "Iseyin",
      "Itesiwaju",
      "Iwajowa",
      "Kajola",
      "Lagelu",
      "Ogbomosho North",
      "Ogbomosho South",
      "Ogo Oluwa",
      "Olorunsogo",
      "Oluyole",
      "Ona Ara",
      "Orelope",
      "Ori Ire",
      "Oyo",
      "Oyo East",
      "Saki East",
      "Saki West",
      "Surulere Oyo State"
    ]
  },
  {
    "state": "Imo",
    "state": "imo",
    "lgas": [
      "Aboh Mbaise",
      "Ahiazu Mbaise",
      "Ehime Mbano",
      "Ezinihitte",
      "Ideato North",
      "Ideato South",
      "Ihitte/Uboma",
      "Ikeduru",
      "Isiala Mbano",
      "Mbaitoli",
      "Isu",
      "Ngor Okpala",
      "Njaba",
      "Nkwerre",
      "Nwangele",
      "Obowo",
      "Oguta",
      "Ohaji/Egbema",
      "Okigwe",
      "Orlu",
      "Orsu",
      "Oru East",
      "Oru West",
      "Owerri Municipal",
      "Owerri North",
      "Unuimo",
      "Owerri West"
    ]
  },
  {
    "state": "Kaduna",
    "state": "kaduna",
    "lgas": [
      "Birnin Gwari",
      "Chikun",
      "Giwa",
      "Ikara",
      "Igabi",
      "Jaba",
      "Jema'a",
      "Kachia",
      "Kaduna North",
      "Kaduna South",
      "Kagarko",
      "Kajuru",
      "Kaura",
      "Kauru",
      "Kubau",
      "Kudan",
      "Lere",
      "Makarfi",
      "Sabon Gari",
      "Sanga",
      "Soba",
      "Zangon Kataf",
      "Zaria"
    ]
  },
  {
    "state": "Kebbi",
    "state": "kebbi",
    "lgas": [
      "Aleiro",
      "Argungu",
      "Arewa Dandi",
      "Augie",
      "Bagudo",
      "Birnin Kebbi",
      "Bunza",
      "Dandi",
      "Fakai",
      "Gwandu",
      "Jega",
      "Kalgo",
      "Koko/Besse",
      "Maiyama",
      "Ngaski",
      "Shanga",
      "Suru",
      "Sakaba",
      "Wasagu/Danko",
      "Yauri",
      "Zuru"
    ]
  },
  {
    "state": "Kano",
    "state": "kano",
    "lgas": [
      "Ajingi",
      "Albasu",
      "Bagwai",
      "Bebeji",
      "Bichi",
      "Bunkure",
      "Dala",
      "Dambatta",
      "Dawakin Kudu",
      "Dawakin Tofa",
      "Doguwa",
      "Fagge",
      "Gabasawa",
      "Garko",
      "Garun Mallam",
      "Gezawa",
      "Gaya",
      "Gwale",
      "Gwarzo",
      "Kabo",
      "Kano Municipal",
      "Karaye",
      "Kibiya",
      "Kiru",
      "Kumbotso",
      "Kunchi",
      "Kura",
      "Madobi",
      "Makoda",
      "Minjibir",
      "Nasarawa",
      "Rano",
      "Rimin Gado",
      "Rogo",
      "Shanono",
      "Takai",
      "Sumaila",
      "Tarauni",
      "Tofa",
      "Tsanyawa",
      "Tudun Wada",
      "Ungogo",
      "Warawa",
      "Wudil"
    ]
  },
  {
    "state": "Kogi",
    "state": "kogi",
    "lgas": [
      "Ajaokuta",
      "Adavi",
      "Ankpa",
      "Bassa",
      "Dekina",
      "Ibaji",
      "Idah",
      "Igalamela Odolu",
      "Ijumu",
      "Kogi",
      "Kabba/Bunu",
      "Lokoja",
      "Ofu",
      "Mopa Muro",
      "Ogori/Magongo",
      "Okehi",
      "Okene",
      "Olamaboro",
      "Omala",
      "Yagba East",
      "Yagba West"
    ]
  },
  {
    "state": "Osun",
    "state": "osun",
    "lgas": [
      "Aiyedire",
      "Atakunmosa West",
      "Atakunmosa East",
      "Aiyedaade",
      "Boluwaduro",
      "Boripe",
      "Ife East",
      "Ede South",
      "Ife North",
      "Ede North",
      "Ife South",
      "Ejigbo",
      "Ife Central",
      "Ifedayo",
      "Egbedore",
      "Ila",
      "Ifelodun",
      "Ilesa East",
      "Ilesa West",
      "Irepodun",
      "Irewole",
      "Isokan",
      "Iwo",
      "Obokun",
      "Odo Otin",
      "Ola Oluwa",
      "Olorunda",
      "Oriade",
      "Orolu",
      "Osogbo"
    ]
  },
  {
    "state": "Sokoto",
    "state": "sokoto",
    "lgas": [
      "Gudu",
      "Gwadabawa",
      "Illela",
      "Isa",
      "Kebbe",
      "Kware",
      "Rabah",
      "Sabon Birni",
      "Shagari",
      "Silame",
      "Sokoto North",
      "Sokoto South",
      "Tambuwal",
      "Tangaza",
      "Tureta",
      "Wamako",
      "Wurno",
      "Yabo",
      "Binji",
      "Bodinga",
      "Dange Shuni",
      "Goronyo",
      "Gada"
    ]
  },
  {
    "state": "Plateau",
    "state": "plateau",
    "lgas": [
      "Bokkos",
      "Barkin Ladi",
      "Bassa",
      "Jos East",
      "Jos North",
      "Jos South",
      "Kanam",
      "Kanke",
      "Langtang South",
      "Langtang North",
      "Mangu",
      "Mikang",
      "Pankshin",
      "Qua'an Pan",
      "Riyom",
      "Shendam",
      "Wase"
    ]
  },
  {
    "state": "Taraba",
    "state": "taraba",
    "lgas": [
      "Ardo Kola",
      "Bali",
      "Donga",
      "Gashaka",
      "Gassol",
      "Ibi",
      "Jalingo",
      "Karim Lamido",
      "Kumi",
      "Lau",
      "Sardauna",
      "Takum",
      "Ussa",
      "Wukari",
      "Yorro",
      "Zing"
    ]
  },
  {
    "state": "Yobe",
    "state": "yobe",
    "lgas": [
      "Bade",
      "Bursari",
      "Damaturu",
      "Fika",
      "Fune",
      "Geidam",
      "Gujba",
      "Gulani",
      "Jakusko",
      "Karasuwa",
      "Machina",
      "Nangere",
      "Nguru",
      "Potiskum",
      "Tarmuwa",
      "Yunusari",
      "Yusufari"
    ]
  },
  {
    "state": "Zamfara",
    "state": "zamfara",
    "lgas": [
      "Anka",
      "Birnin Magaji/Kiyaw",
      "Bakura",
      "Bukkuyum",
      "Bungudu",
      "Gummi",
      "Gusau",
      "Kaura Namoda",
      "Maradun",
      "Shinkafi",
      "Maru",
      "Talata Mafara",
      "Tsafe",
      "Zurmi"
    ]
  },
  {
    "state": "Lagos",
    "state": "lagos",
    "lgas": [
      "Agege",
      "Ajeromi-Ifelodun",
      "Alimosho",
      "Amuwo-Odofin",
      "Badagry",
      "Apapa",
      "Epe",
      "Eti Osa",
      "Ibeju-Lekki",
      "Ifako-Ijaiye",
      "Ikeja",
      "Ikorodu",
      "Kosofe",
      "Lagos Island",
      "Mushin",
      "Lagos Mainland",
      "Ojo",
      "Oshodi-Isolo",
      "Shomolu",
      "Surulere Lagos State"
    ]
  },
  {
    "state": "Katsina",
    "state": "katsina",
    "lgas": [
      "Bakori",
      "Batagarawa",
      "Batsari",
      "Baure",
      "Bindawa",
      "Charanchi",
      "Danja",
      "Dandume",
      "Dan Musa",
      "Daura",
      "Dutsi",
      "Dutsin Ma",
      "Faskari",
      "Funtua",
      "Ingawa",
      "Jibia",
      "Kafur",
      "Kaita",
      "Kankara",
      "Kankia",
      "Katsina",
      "Kurfi",
      "Kusada",
      "Mai'Adua",
      "Malumfashi",
      "Mani",
      "Mashi",
      "Matazu",
      "Musawa",
      "Rimi",
      "Sabuwa",
      "Safana",
      "Sandamu",
      "Zango"
    ]
  },
  {
    "state": "Kwara",
    "state": "kwara",
    "lgas": [
      "Asa",
      "Baruten",
      "Edu",
      "Ilorin East",
      "Ifelodun",
      "Ilorin South",
      "Ekiti Kwara State",
      "Ilorin West",
      "Irepodun",
      "Isin",
      "Kaiama",
      "Moro",
      "Offa",
      "Oke Ero",
      "Oyun",
      "Pategi"
    ]
  },
  {
    "state": "Nasarawa",
    "state": "nasarawa",
    "lgas": [
      "Akwanga",
      "Awe",
      "Doma",
      "Karu",
      "Keana",
      "Keffi",
      "Lafia",
      "Kokona",
      "Nasarawa Egon",
      "Nasarawa",
      "Obi",
      "Toto",
      "Wamba"
    ]
  },
  {
    "state": "Niger",
    "state": "niger",
    "lgas": [
      "Agaie",
      "Agwara",
      "Bida",
      "Borgu",
      "Bosso",
      "Chanchaga",
      "Edati",
      "Gbako",
      "Gurara",
      "Katcha",
      "Kontagora",
      "Lapai",
      "Lavun",
      "Mariga",
      "Magama",
      "Mokwa",
      "Mashegu",
      "Moya",
      "Paikoro",
      "Rafi",
      "Rijau",
      "Shiroro",
      "Suleja",
      "Tafa",
      "Wushishi"
    ]
  },
  {
    "state": "Abia",
    "state": "abia",
    "lgas": [
      "Aba North",
      "Arochukwu",
      "Aba South",
      "Bende",
      "Isiala Ngwa North",
      "Ikwuano",
      "Isiala Ngwa South",
      "Isuikwuato",
      "Obi Ngwa",
      "Ohafia",
      "Osisioma",
      "Ugwunagbo",
      "Ukwa East",
      "Ukwa West",
      "Umuahia North",
      "Umuahia South",
      "Umu Nneochi"
    ]
  }
]
